"""CRF - Context Reasoning Format Python Library."""

from crf.models import (
    AdoptionStatus,
    ArchitectureAttributes,
    ArchitectureType,
    CapabilityAttributes,
    CapabilityType,
    ContextDocument,
    Criticality,
    DataClassification,
    Enforcement,
    Entity,
    EntityType,
    FactAttributes,
    FactType,
    Maturity,
    OrganizationAttributes,
    OrgSize,
    OrgType,
    PolicyAttributes,
    PolicyType,
    Proficiency,
    Provenance,
    CRFRelationship,
    RelationshipType,
    StrategicImportance,
    Supersedes,
    SystemAttributes,
    SystemStatus,
    SystemType,
    Validity,
)

__version__ = "0.1.0"
__all__ = [
    # Main document
    "ContextDocument",
    "Entity",
    # Sub-components
    "Validity",
    "CRFRelationship",
    "Supersedes",
    "Provenance",
    # Attribute types
    "OrganizationAttributes",
    "SystemAttributes",
    "PolicyAttributes",
    "FactAttributes",
    "ArchitectureAttributes",
    "CapabilityAttributes",
    # Enums
    "EntityType",
    "RelationshipType",
    "OrgType",
    "OrgSize",
    "SystemType",
    "SystemStatus",
    "Criticality",
    "DataClassification",
    "PolicyType",
    "Enforcement",
    "FactType",
    "ArchitectureType",
    "Maturity",
    "AdoptionStatus",
    "CapabilityType",
    "Proficiency",
    "StrategicImportance",
]
